### ISSUE TITLE
As a user I would like to add content to my TODO descriptions from markdown templates stored in my project   

### ISSUE THREAD

**Issue by piascikj** [imdone/imdone-atom#322]
- [ ] Append templates to tasks with `t:<type>` metadata in them. (e.g. `t:story`)
    - [ ] if TODO appears in a single line comment, append template with single line comment prefix and the same indentation as the TODO comment
    - [ ] If TODO appears in a multiline comment, just append template at the same indentation as the TODO comment
    - [ ] Remove `t:story` after the template has been appended to the description
  - [x] templates.md will contain templates in the format...
  ```
  # <type>
  Any markdown for your template
  ```

----
*opened via [imdone.io](https://imdone.io) from a code comment on [ab5ceea1](https://github.com/imdone/imdone-atom/commit/ab5ceea1) by Jesse*

----

https://github.com/imdone/imdone-atom/blob/f9738b452952ccdeaf2b6e78944686e23eba53b2/todo.md#L5-L19

**Comment by piascikj** [comment]
Issue closed with imdone.io by removing a comment.

----

https://github.com/imdone/imdone-atom/blob/729c88d5c2b7a6fe241f0f1eb2f94f821f463b3a/todo.md#L5-L19
